version: '3.9'

services:
  web:
    container_name: wb_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - src/data/.env
    depends_on:
      - wild_db
    command: bash -c 'alembic upgrade head && cd src/ && python3 app.py'

  bot:
    container_name: wb_bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - src/data/.env
    depends_on:
      - wild_db
    command: bash -c 'cd src/bot/ && python3 main.py'
      
  wild_db:
    image: postgres:15
    env_file:
      - src/data/.env
    ports:
      - "5433:5432"
    volumes:
      - .postgres:/var/lib/postgresql/data