services:
  web:
    container_name: wb_api
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - ../.env
    depends_on:
      - wild_db
    command: bash -c 'source .venv/bin/activate && alembic upgrade head && python3 main.py'

  # bot:
  #   container_name: wb_bot
  #   build:
  #     context: ..
  #     dockerfile: deploy/Dockerfile
  #   env_file:
  #     - ../.env
  #   depends_on:
  #     - wild_db
  #   command: bash -c 'source .venv/bin/activate && python3 bot/main.py'
      
  wild_db:
    image: postgres:15
    env_file:
      - ../.env
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: