"""empty message

Revision ID: d2b723519c34
Revises: 
Create Date: 2025-01-20 19:27:49.846687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2b723519c34'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('article', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('price', sa.BigInteger(), nullable=True),
    sa.Column('rating', sa.BigInteger(), nullable=True),
    sa.Column('total_quantity', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('article'),
    sa.UniqueConstraint('article')
    )
    op.create_table('schedule_product',
    sa.Column('article', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('article'),
    sa.UniqueConstraint('article')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_product')
    op.drop_table('product')
    # ### end Alembic commands ###
